
if(!window.AndroidBridge){window.AndroidBridge={pickVideos(){setStatus('Use pelo APK para escolher vídeos.')},pickAudio(){setStatus('Use pelo APK para escolher música.')},pickImages(){setStatus('Use pelo APK para escolher imagens.')},exportVideo(j){console.log(j);setStatus('Simulação de exportação no navegador.')}}}
let videos=[],images=[],texts=[],markers=[],audio=null,selected=0,playQueue=false,autosaveTimer=null,historyStack=[],redoStack=[],isRestoringHistory=false;
const preview=document.getElementById('preview'),audioEl=document.getElementById('audioPreview'),wrap=document.getElementById('previewWrap');
preview.addEventListener('timeupdate',()=>{document.getElementById('seek').value=preview.duration?Math.round((preview.currentTime/preview.duration)*1000):0;document.getElementById('timeLabel').innerText=fmt(preview.currentTime*1000);syncOverlays()});
preview.addEventListener('ended',()=>{if(playQueue)playNextInQueue();else document.getElementById('playBtn').innerText='Play'});
function fmt(ms){ms=Number(ms)||0;let s=Math.floor(ms/1000),m=Math.floor(s/60);s=s%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function setStatus(t){document.getElementById('status').innerText=t}
function scheduleSave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>saveProject(true),600)}
function baseClip(v,i){return {...v,uid:'v'+Date.now()+i+Math.random().toString(16).slice(2),transition:'none',transitionMs:500,trimStart:0,trimEnd:100,volume:100,speed:1,order:i}}
function setProjectVideos(arr){videos=(arr||[]).map(baseClip);selected=0;render();loadPreview(0);setStatus(videos.length+' vídeo(s) na timeline.');saveProject(true)}
function setProjectImages(arr){images=(arr||[]).map((img,i)=>({...img,uid:'i'+Date.now()+i,start:0,duration:3000,order:i,x:82,y:16,size:32,opacity:100}));render();syncOverlays();saveProject(true)}
function setAudioTrack(a){audio={...a,start:0,durationMs:a.durationMs||0,volume:80,fade:'none'};audioEl.src=a.previewUrl||a.uri;audioEl.style.display='block';render();setStatus('Música adicionada: '+a.name);saveProject(true)}
function loadPreview(i){if(!videos[i])return;selected=i;const v=videos[i];preview.src=v.previewUrl||v.uri;preview.style.display='block';document.getElementById('emptyPreview').style.display='none';document.getElementById('selectedLabel').innerText=v.name;document.getElementById('clipInfo').innerText=fmt(v.durationMs||0);document.getElementById('clipName').value=v.name||'';document.getElementById('trimStart').value=v.trimStart||0;document.getElementById('trimEnd').value=v.trimEnd||100;document.getElementById('clipVolume').value=v.volume??100;document.getElementById('clipSpeed').value=String(v.speed||1);document.getElementById('transitionSelect').value=v.transition||'none';document.getElementById('transitionDuration').value=String(v.transitionMs||500);preview.playbackRate=Number(v.speed||1);preview.volume=(v.volume??100)/100;applyTransitionFx(v.transition);render();syncOverlays();scheduleSave()}
function applyTransitionFx(t){wrap.className='preview-wrap';if(t&&t!=='none')wrap.classList.add('fx-'+t)}
function clipDuration(v){let d=v.durationMs||0;let pct=Math.max(0,(v.trimEnd??100)-(v.trimStart??0))/100;return Math.round((d*pct)/(Number(v.speed||1)||1))}
function totalDuration(){return videos.reduce((a,v)=>a+clipDuration(v),0)}
function render(){document.getElementById('projectInfo').innerText=videos.length+' vídeo(s)';document.getElementById('totalDuration').innerText=fmt(totalDuration());let zoom=Number(document.getElementById('zoom')?.value||160);let vt=document.getElementById('videoTrack');vt.innerHTML='';if(!videos.length)vt.innerHTML='<span class="hint">Nenhum vídeo na timeline.</span>';videos.forEach((v,i)=>{let el=document.createElement('div');el.className='clip '+(i===selected?'active':'');el.style.minWidth=Math.max(110,Math.min(360,zoom*(clipDuration(v)/Math.max(1000,totalDuration()/Math.max(1,videos.length)))))+'px';el.onclick=()=>loadPreview(i);el.innerHTML='<div class="name">'+escapeHtml(v.name)+'</div><div class="dur">'+fmt(clipDuration(v))+'</div><div class="meta">Corte '+(v.trimStart||0)+'% - '+(v.trimEnd||100)+'% • '+(v.speed||1)+'x</div><div class="meta">Volume '+(v.volume??100)+'% • '+transLabel(v)+'</div><div class="clip-tools"><button onclick="event.stopPropagation();moveClipAt('+i+',-1)">◀</button><button onclick="event.stopPropagation();loadPreview('+i+')">Ver</button><button onclick="event.stopPropagation();moveClipAt('+i+',1)">▶</button></div>';vt.appendChild(el)});
let tr=document.getElementById('transitionTrack');let trans=videos.map((v,i)=>({v,i})).filter(x=>x.v.transition&&x.v.transition!=='none');tr.innerHTML=trans.length?trans.map(x=>'<div class="clip"><div class="name">'+escapeHtml(x.v.transition)+'</div><div class="dur">após clipe '+(x.i+1)+'</div><div class="meta">'+((x.v.transitionMs||500)/1000)+'s</div></div>').join(''):'<span class="hint">Sem transições.</span>';
let mt=document.getElementById('musicTrack');mt.innerHTML=audio?'<div class="clip music-clip"><div class="name">♫ '+escapeHtml(audio.name)+'</div><div class="dur">'+fmt(audio.durationMs)+'</div><div class="meta">Volume '+(audio.volume||80)+'% • '+(audio.fade||'none')+'</div></div>':'<span class="hint">Sem música.</span>';document.getElementById('audioLabel').innerText=audio?audio.name:'Sem música';
let tt=document.getElementById('textTrack');tt.innerHTML=texts.length?texts.map((t,i)=>'<div class="clip text-clip" onclick="selectText('+i+')"><div class="name">T'+(i+1)+': '+escapeHtml(t.text)+'</div><div class="dur">'+fmt(t.duration)+'</div><div class="meta">'+t.style+' • '+t.size+'px</div></div>').join(''):'<span class="hint">Sem texto.</span>';
let it=document.getElementById('imageTrack');it.innerHTML=images.length?images.map((im,i)=>'<div class="clip image-clip"><div class="name">Imagem '+(i+1)+'</div><div class="dur">'+escapeHtml(im.name)+'</div><div class="meta">'+(im.size||32)+'% • opacidade '+(im.opacity||100)+'%</div></div>').join(''):'<span class="hint">Sem imagem.</span>';syncOverlays()}
function transLabel(v){return (v.transition==='none'?'Sem transição':v.transition)+' • '+((v.transitionMs||500)/1000)+'s'}
function escapeHtml(s){return String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function moveClipAt(i,dir){pushHistory();let ni=i+dir;if(ni<0||ni>=videos.length)return;[videos[i],videos[ni]]=[videos[ni],videos[i]];selected=ni;render();setStatus('Ordem da timeline atualizada.');scheduleSave()}
function moveClip(dir){moveClipAt(selected,dir)}
function jumpClip(dir){if(!videos.length)return;let ni=Math.max(0,Math.min(videos.length-1,selected+dir));loadPreview(ni)}
function duplicateClip(){if(!videos[selected])return;pushHistory();videos.splice(selected+1,0,{...videos[selected],uid:'v'+Date.now(),name:videos[selected].name+' cópia'});selected++;render();loadPreview(selected);setStatus('Clipe duplicado.');scheduleSave()}
function removeClip(){if(!videos[selected])return;pushHistory();videos.splice(selected,1);selected=Math.max(0,selected-1);render();if(videos[selected])loadPreview(selected);else{preview.pause();preview.removeAttribute('src');preview.style.display='none';document.getElementById('emptyPreview').style.display='block'}setStatus('Clipe excluído.');scheduleSave()}
function renameClip(n){if(videos[selected]){videos[selected].name=n||videos[selected].name;render();scheduleSave()}}
function updateClipEdit(){if(!videos[selected])return;pushHistory();let v=videos[selected];v.trimStart=Number(document.getElementById('trimStart').value);v.trimEnd=Math.max(v.trimStart+1,Number(document.getElementById('trimEnd').value));document.getElementById('trimEnd').value=v.trimEnd;v.volume=Number(document.getElementById('clipVolume').value);v.speed=Number(document.getElementById('clipSpeed').value);v.transition=document.getElementById('transitionSelect').value;v.transitionMs=Number(document.getElementById('transitionDuration').value);preview.playbackRate=v.speed;preview.volume=v.volume/100;applyTransitionFx(v.transition);render();setStatus('Edição do clipe atualizada.');scheduleSave()}
function currentPercent(){return preview.duration?Math.round((preview.currentTime/preview.duration)*100):0}
function setTrimByCurrent(which){if(!videos[selected]||!preview.duration)return;let p=currentPercent();if(which==='start')document.getElementById('trimStart').value=Math.min(90,p);else document.getElementById('trimEnd').value=Math.max(10,p);updateClipEdit()}
function resetTrim(){document.getElementById('trimStart').value=0;document.getElementById('trimEnd').value=100;updateClipEdit()}
function splitSelectedClip(){pushHistory();let v=videos[selected];if(!v||!preview.duration){setStatus('Dê play ou posicione o cursor no clipe.');return}let p=currentPercent();let a={...v,uid:'v'+Date.now()+'a',name:v.name+' parte 1',trimEnd:p};let b={...v,uid:'v'+Date.now()+'b',name:v.name+' parte 2',trimStart:p};if(p<=v.trimStart||p>=v.trimEnd){setStatus('Posicione o cursor dentro do trecho válido do clipe.');return}videos.splice(selected,1,a,b);render();loadPreview(selected+1);setStatus('Clipe dividido em duas partes.');scheduleSave()}
function togglePlay(){if(!preview.src){setStatus('Escolha um vídeo primeiro.');return} if(preview.paused){preview.play();if(audio&&audioEl.paused)try{audioEl.play()}catch(e){}document.getElementById('playBtn').innerText='Pause'}else{preview.pause();audioEl.pause();document.getElementById('playBtn').innerText='Play'}}
function seekPreview(v){if(preview.duration)preview.currentTime=(Number(v)/1000)*preview.duration}
function seekMaster(v){let target=(Number(v)/1000)*totalDuration(),acc=0;for(let i=0;i<videos.length;i++){let d=clipDuration(videos[i]);if(target<=acc+d){loadPreview(i);let local=(target-acc)/Math.max(1,d);preview.onloadedmetadata=()=>{preview.currentTime=local*preview.duration};break}acc+=d}}
function previewAll(){if(!videos.length){setStatus('Sem vídeos na timeline.');return}playQueue=true;selected=-1;audioEl.currentTime=Number(document.getElementById('musicStart')?.value||0);try{if(audio)audioEl.play()}catch(e){}playNextInQueue()}
function playNextInQueue(){selected++;if(selected>=videos.length){playQueue=false;selected=0;audioEl.pause();render();setStatus('Preview da timeline finalizado.');return}loadPreview(selected);setTimeout(()=>preview.play(),250)}
function clearAudio(){pushHistory();audio=null;audioEl.pause();audioEl.removeAttribute('src');audioEl.style.display='none';render();setStatus('Música removida.');scheduleSave()}
function syncAudioSettings(){if(audio){pushHistory();audio.volume=Number(document.getElementById('musicVolume').value);audio.fade=document.getElementById('musicFade').value;audio.start=Number(document.getElementById('musicStart').value||0)*1000;audio.customDuration=Number(document.getElementById('musicDuration').value||0)*1000;audioEl.volume=audio.volume/100;render();scheduleSave()}}
function addTextLayer(){pushHistory();let t=document.getElementById('textContent').value.trim();if(!t)return;texts.push({text:t,style:document.getElementById('textStyle').value,color:document.getElementById('textColor').value,size:Number(document.getElementById('textSize').value||30),x:Number(document.getElementById('textX').value),y:Number(document.getElementById('textY').value),start:0,duration:Number(document.getElementById('textDuration').value||3)*1000});document.getElementById('textContent').value='';render();syncOverlays();setStatus('Texto adicionado.');scheduleSave()}
function selectText(i){let t=texts[i];if(!t)return;document.getElementById('textContent').value=t.text;document.getElementById('textStyle').value=t.style;document.getElementById('textColor').value=t.color||'#fff';document.getElementById('textSize').value=t.size||30;document.getElementById('textX').value=t.x||50;document.getElementById('textY').value=t.y||72;tab('text')}
function clearTexts(){pushHistory();texts=[];render();syncOverlays();setStatus('Textos removidos.');scheduleSave()}
function clearImages(){pushHistory();images=[];render();syncOverlays();setStatus('Imagens removidas.');scheduleSave()}
function syncOverlays(){let txt=document.getElementById('textOverlay');let activeText=texts[0];if(activeText){txt.style.display='block';txt.innerText=activeText.text;txt.style.color=activeText.color||'#fff';txt.style.fontSize=(activeText.size||30)+'px';txt.style.left=(activeText.x||50)+'%';txt.style.top=(activeText.y||72)+'%';if(activeText.style==='impact')txt.style.color='#ffcc33';if(activeText.style==='sale')txt.style.color='#ff4d5d';if(activeText.style==='subtitle'){txt.style.top='84%';txt.style.fontSize='22px'}}else txt.style.display='none';let img=document.getElementById('imageOverlay');if(images[0]){let im=images[0];im.x=Number(document.getElementById('imgX')?.value||im.x||82);im.y=Number(document.getElementById('imgY')?.value||im.y||16);im.size=Number(document.getElementById('imgSize')?.value||im.size||32);im.opacity=Number(document.getElementById('imgOpacity')?.value||im.opacity||100);img.src=im.previewUrl||im.uri;img.style.display='block';img.style.left=im.x+'%';img.style.top=im.y+'%';img.style.right='auto';img.style.maxWidth=im.size+'%';img.style.maxHeight=im.size+'%';img.style.opacity=im.opacity/100}else img.style.display='none'}
function applyFilter(){let b=document.getElementById('brightRange').value,c=document.getElementById('contrastRange').value,f=document.getElementById('filterSelect').value;let extra='';if(f==='bw')extra=' grayscale(1)';if(f==='warm')extra=' sepia(.25) saturate(1.25)';if(f==='cool')extra=' hue-rotate(190deg) saturate(1.15)';if(f==='bright')b=130;if(f==='contrast')c=145;preview.style.filter='brightness('+b+'%) contrast('+c+'%)'+extra}
function tab(name,btn){document.querySelectorAll('.tool-panel').forEach(p=>p.classList.remove('active'));let p=document.getElementById('panel-'+name);if(p)p.classList.add('active');document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active')}

function pushHistory(){if(isRestoringHistory)return;try{historyStack.push(JSON.stringify({videos,audio,texts,images,markers,selected}));if(historyStack.length>40)historyStack.shift();redoStack=[]}catch(e){}}
function snapshotManual(){pushHistory();saveProject(false);setStatus('Ponto de restauração salvo.');}
function undo(){if(!historyStack.length){setStatus('Nada para desfazer.');return}try{redoStack.push(JSON.stringify({videos,audio,texts,images,markers,selected}));let last=historyStack.pop();isRestoringHistory=true;restoreFromObject(JSON.parse(last));isRestoringHistory=false;setStatus('Desfeito.')}catch(e){isRestoringHistory=false;setStatus('Erro ao desfazer: '+e.message)}}
function redo(){if(!redoStack.length){setStatus('Nada para refazer.');return}try{historyStack.push(JSON.stringify({videos,audio,texts,images,markers,selected}));let next=redoStack.pop();isRestoringHistory=true;restoreFromObject(JSON.parse(next));isRestoringHistory=false;setStatus('Refeito.')}catch(e){isRestoringHistory=false;setStatus('Erro ao refazer: '+e.message)}}
function restoreFromObject(p){videos=p.videos||[];audio=p.audio||null;texts=p.texts||[];images=p.images||[];markers=p.markers||[];markers=p.markers||[];selected=Math.max(0,Math.min(p.selected||0,videos.length-1));if(audio){audioEl.src=audio.previewUrl||audio.uri;audioEl.style.display='block'}else{audioEl.pause();audioEl.removeAttribute('src');audioEl.style.display='none'}render();if(videos[selected])loadPreview(selected);else{preview.pause();preview.removeAttribute('src');preview.style.display='none';document.getElementById('emptyPreview').style.display='block'}syncOverlays();}
function applyBulkTransition(){pushHistory();let t=document.getElementById('bulkTransition').value;videos.forEach(v=>{v.transition=t;v.transitionMs=Number(document.getElementById('transitionDuration')?.value||500)});render();if(videos[selected])loadPreview(selected);setStatus('Transição aplicada em todos os clipes.');scheduleSave()}
function normalizeClips(){pushHistory();videos.forEach(v=>{v.volume=100;v.speed=1;if(v.trimEnd<=v.trimStart){v.trimStart=0;v.trimEnd=100}});render();if(videos[selected])loadPreview(selected);setStatus('Clipes normalizados: volume 100%, velocidade 1x e cortes válidos.');scheduleSave()}
function addMarker(){let name=(document.getElementById('markerName').value||'Marcador').trim();let at=0;for(let i=0;i<selected;i++)at+=clipDuration(videos[i]);if(preview.duration)at+=preview.currentTime*1000;markers.push({name,at:Math.round(at)});document.getElementById('markerName').value='';renderMarkers();scheduleSave();setStatus('Marcador adicionado: '+name)}
function removeMarker(i){markers.splice(i,1);renderMarkers();scheduleSave()}
function renderMarkers(){let el=document.getElementById('markersList');if(!el)return;el.innerHTML=markers.length?markers.map((m,i)=>'<span class="marker">'+fmt(m.at)+' • '+escapeHtml(m.name)+' <button class="red" style="padding:3px 7px;margin-left:5px" onclick="removeMarker('+i+')">x</button></span>').join(''):'<span class="hint">Sem marcadores.</span>'}
function copyProjectJson(){let data=JSON.stringify(projectData(),null,2);try{navigator.clipboard.writeText(data);setStatus('JSON do projeto copiado.')}catch(e){prompt('Copie o JSON do projeto:',data)}}
document.addEventListener('keydown',e=>{if(e.target&&['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay()}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if(e.key==='Delete'){removeClip()}});

function projectData(){return {version:'S4',savedAt:new Date().toISOString(),videos,audio,texts,images,markers,settings:{preset:document.getElementById('preset').value,quality:document.getElementById('quality').value,fileName:document.getElementById('fileName').value}}}
function saveProject(silent=false){try{localStorage.setItem('tradeup_project_s4',JSON.stringify(projectData()));if(!silent)setStatus('Projeto salvo no aparelho.')}catch(e){setStatus('Erro ao salvar projeto: '+e.message)}}
function restoreProject(){try{let raw=localStorage.getItem('tradeup_project_s4');if(!raw){setStatus('Nenhum projeto salvo neste aparelho.');return}let p=JSON.parse(raw);videos=p.videos||[];audio=p.audio||null;texts=p.texts||[];images=p.images||[];markers=p.markers||[];if(audio){audioEl.src=audio.previewUrl||audio.uri;audioEl.style.display='block'}selected=0;render();if(videos[0])loadPreview(0);syncOverlays();setStatus('Projeto restaurado do aparelho.')}catch(e){setStatus('Erro ao restaurar: '+e.message)}}
function newProject(){if(!confirm('Limpar projeto atual?'))return;pushHistory();videos=[];audio=null;images=[];texts=[];selected=0;preview.pause();audioEl.pause();preview.removeAttribute('src');audioEl.removeAttribute('src');preview.style.display='none';audioEl.style.display='none';document.getElementById('emptyPreview').style.display='block';render();syncOverlays();setStatus('Novo projeto iniciado.');saveProject(true)}
function exportar(){let name=document.getElementById('fileName').value||'video_tradeup_v4';let job=projectData();job.fileName=name;job.durationMs=totalDuration();if(window.AndroidBridge){AndroidBridge.exportVideo(JSON.stringify(job))}else setStatus('Abra pelo APK para exportar.')}
function setExportProgress(pct,msg){document.getElementById('exportBox').style.display='block';document.getElementById('exportBar').style.width=Math.max(0,Math.min(100,pct))+'%';document.getElementById('exportText').innerText=msg;setStatus(msg)}
render();setTimeout(()=>restoreProject(),400);
